import { DollarSign, TrendingUp, Users, PieChart as PieChartIcon, ArrowUpRight } from "lucide-react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

const IMPACT_DATA = [
    { month: "Jan", savings: 12000 },
    { month: "Feb", savings: 15500 },
    { month: "Mar", savings: 18000 },
    { month: "Apr", savings: 24000 },
    { month: "May", savings: 32000 },
    { month: "Jun", savings: 45000 },
];

export default function BusinessImpact() {
    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-white">Business Impact & Analytics</h1>
                    <p className="text-slate-400">Track the ROI and value generated by your AI models.</p>
                </div>
                <Button variant="outline" className="gap-2">
                    Download Report
                </Button>
            </div>

            <div className="grid md:grid-cols-4 gap-6">
                {[
                    { label: "Total Cost Savings", value: "$146,500", icon: DollarSign, trend: "+24%", color: "text-green-500" },
                    { label: "Predictions Served", value: "2.4M", icon: TrendingUp, trend: "+12%", color: "text-blue-500" },
                    { label: "Man-hours Saved", value: "850 hrs", icon: Users, trend: "+5%", color: "text-purple-500" },
                    { label: "Model Accuracy", value: "94.2%", icon: PieChartIcon, trend: "+0.8%", color: "text-orange-500" },
                ].map((stat, i) => (
                    <Card key={i}>
                        <CardContent className="p-6">
                            <div className="flex justify-between items-start mb-4">
                                <div className={`p-2 rounded-lg bg-white/5 ${stat.color}`}>
                                    <stat.icon className="w-5 h-5" />
                                </div>
                                <div className="flex items-center gap-1 text-xs font-semibold text-green-500 bg-green-500/10 px-2 py-1 rounded-full">
                                    {stat.trend} <ArrowUpRight className="w-3 h-3" />
                                </div>
                            </div>
                            <div className="text-2xl font-bold text-white">{stat.value}</div>
                            <div className="text-sm text-slate-500">{stat.label}</div>
                        </CardContent>
                    </Card>
                ))}
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Cumulative Cost Savings (YTD)</CardTitle>
                    <CardDescription>Estimated savings based on automated decisions replacing manual review.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="h-[400px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={IMPACT_DATA}>
                                <defs>
                                    <linearGradient id="colorSavings" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#22c55e" stopOpacity={0.3} />
                                        <stop offset="95%" stopColor="#22c55e" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <XAxis dataKey="month" stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} />
                                <YAxis stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value / 1000}k`} />
                                <Tooltip
                                    contentStyle={{ backgroundColor: "#1e293b", borderColor: "#334155", borderRadius: "8px", color: "white" }}
                                />
                                <Area type="monotone" dataKey="savings" stroke="#22c55e" fillOpacity={1} fill="url(#colorSavings)" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
